"Author	: Clement "DraZoro" Mahlangu
"Date	: 15 May 2026

call plug#begin()

set nocompatible
filetype off

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-sensible'
" TODO: snippets
" Plug 'SirVer/ultisnips'  
" Plug 'scrooloose/nerdtree'
" Plug 'scrooloose/syntastic'
" Plug 'Valloric/YouCompleteMe'
" Plug 'Valloric/Vim-Jinja2-Syntax'
" Plug 'sukima/xmledit'
" Plug 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
" Plug 'digitaltoad/vim-jade'
" Plug 'anyakichi/vim-surround'
" Plug 'Raimondi/delimitMate'
" Plug 'jelera/vim-javascript-syntax'
" Plug 'nathanaelkane/vim-indent-guides'
Plug 'sjl/badwolf'
" Plug 'lervag/vimtex'

call plug#end()


filetype plugin on 

" Modeline for python
autocmd FileType python set sw=4
autocmd FileType python set ts=4
autocmd FileType python set sts=4

" Some colourful things here "
set t_Co=256
syntax on
set background=dark
colorscheme badwolf


" Allow auto indentation
set autoindent 

" Keeping track of location 
set cursorline 
set cursorcolumn

" Ignore case when searching"
set ignorecase 

" Reduce shiftwidth
set shiftwidth=2

" Highlight the searched item
set hlsearch

" Encoding "
set encoding=utf8
" Show location of cursor 
set ruler 

"s All numbers are decimal system. 
set nrformats=

" Spelling settings
" set spell
set spelllang=en
set spellsuggest=5

" Increased search history
set history=100

" Show numbers
set number

" Matching brackets 
set showmatch 

" Make tab to cover four characters of space
set softtabstop=2

" Set grep to always generate a file-name "
set grepprg=grep\ -nH\ $*

" Settings for vim-flagship
set laststatus=2
set showtabline=2
set guioptions-=e


" Some short cut keys "
" nmap <silent> <F3> :NERDTreeToggle<CR>

" Shortcuts for moving between tabs
" Alet-j to move to the tab to the left 
" nmap <A-j> gT
" Alt-k to move to the tab to the right
" nmap <A-k> gt

" Plugin configurations "
"
" Powerline 

" let g:powerline_symbols = "fancy"

" YouCompleteMe "
" let g:ycm_add_preview_to_complteopt=0
" let g:ycm_collect_identifiers_from_tags_files = 1 
" let g:ycm_use_ultisnips_completer = 1 
" let g:ycm_seed_identifiers_with_syntax = 1 
" let g:ycm_complete_in_comments = 1 
" let g:ycm_complete_in_strings = 1 
" set completeopt-=preview
" Ultasnips "
" let g:UltiSnipsExpandTrigger       = "<c-j>"
" let g:UltiSnipsJumpForwardTrigger  = "<c-j>"
" let g:UltiSnipsJumpBackwardTrigger = "<c-p>"
" let g:UltiSnipsListSnippets        = "<c-k>" "List possible snippets based on current file
" let g:UltiSnipsUsePythonVersion    = 2

" Flagship "
" let g:tablabel = "%N%{flagship#tabmodified()} %{flagship#tabcwds('shorten',',')}"
" let g:tabprefix ='%{flagship#id()}'

" Syntastic "
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0

" Number Toggle 
let g:NumberToggleTrigger="<F5>"
