source ~/bin/antigen.zsh

# Load oh-my-zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle kennethreitz/autoenv

antigen apply

ZSH_THEME="amuse"

export ZSH=/home/drazoro/.oh-my-zsh
export PYTHONSTARTUP=~/.pythonrc

export DISABLE_AUTO_TITLE="true"
# plugins=(git python)
# My Configs
export PATH=$HOME/bin/eclipse:$PATH

source $ZSH/oh-my-zsh.sh


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# My personal alias
alias vim=nvim
alias tmux="tmux -2"

# tmuxinator compilation
source ~/.bin/tmuxinator.zsh

# Settings relating to Python Virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export VIRTUALENVWRAPPER_TMPDIR='~/.cache/virtualenvs'
source /usr/local/bin/virtualenvwrapper.sh

SSH_ENV=$HOME/.ssh/environment

# Start the ssh-agent
function start_agent {
    echo "Initializing new SSH agent..."
    # spawn ssh-agent
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add
}

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
	start_agent;
    }
else
    start_agent;
fi
